# Generated by Django 5.2.11 on 2026-03-22 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=180, verbose_name='Job Opening Title')),
                ('description', models.TextField(verbose_name='Job Opening Description')),
                ('start_at', models.DateTimeField(verbose_name='Job Opening Start Date')),
                ('finish_at', models.DateTimeField(verbose_name='Job Opening Finish Date')),
                ('type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship')], default='full_time', max_length=10, verbose_name='Job type')),
                ('location', models.CharField(choices=[('on_site', 'On Site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='on_site', max_length=10, verbose_name='Job location')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('skills', models.ManyToManyField(related_name='job_openings', to='job.skill', verbose_name='Job Opening Skills')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'Job Opening',
                'verbose_name_plural': 'Job Openings',
                'db_table': 'job_opening',
                'ordering': ['-created_at'],
            },
        ),
    ]
