# Generated by Django 5.2.11 on 2026-03-22 14:45

import django.db.models.deletion
import job.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobopening'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('contact_email', models.EmailField(max_length=120, verbose_name='User contact email')),
                ('curriculum', models.FileField(upload_to=job.utils.jobs_curriculum_path, verbose_name='User Curriculum')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='job.jobopening', verbose_name='Job')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='User onwer of enrollment')),
            ],
            options={
                'verbose_name': 'job enrollment',
                'verbose_name_plural': 'jobs enrollments',
                'db_table': 'job_enrollments',
                'ordering': ['-created_at'],
                'unique_together': {('job', 'user')},
            },
        ),
    ]
