# Generated by Django 5.2.11 on 2026-03-20 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(help_text="user name , can't be blank", max_length=120, verbose_name='User name')),
                ('description', models.CharField(blank=True, max_length=120, verbose_name='User description')),
                ('about', models.TextField(blank=True, help_text='About user text , can be blank', verbose_name='About user')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/profile/image/%Y/%m/', verbose_name='User profile photo')),
                ('contact_email', models.CharField(blank=True, max_length=120, verbose_name='User contact email')),
                ('contact_phone_number', models.CharField(blank=True, max_length=13, verbose_name='User contact phone number')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User onwer of profile')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'Users Profiles',
                'db_table': 'profile',
                'ordering': ['created_at'],
            },
        ),
    ]
