# Generated by Django 5.2.11 on 2026-03-21 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.skill')),
            ],
            options={
                'unique_together': {('profile', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(related_name='profiles', through='account.ProfileSkill', to='job.skill', verbose_name='User skills'),
        ),
    ]
